[package]
name = "demohäsä"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14.0"
glutin = "0.29.1"
image = "0.24.3"
cgmath = "0.18.0"
rand = "0.8.5"